# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3905527b842cc0146313dadbe2629cfd6b29ea1fcc6aaff0e2423a214f7713b881f55d17cf77837cab73bfc880b8fb319d56bc5d77e08c274ca027830bcd600

test:
  secret_key_base: c6cc2837beee555afb7c6ed1c7bc12626ec01ea078491f86f1b1cbf663348b38b9efc3fd2467c5cfbc243a4df9df31461bafd4754aa80c4cd750e9ba3e8093e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
