# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b76c4a2189480da6bae7d928f5c4ab6d633f21751f18d95961bf7c835611710fdd5070954238eac186bf526b0ee11b2c03c51a556109275cb23f4da8873c0fbc

test:
  secret_key_base: 142dd393f12a8fef326e67298cd9761f8aded24477da0696da63f10ce9675ff361547ae065934558b05a2671653a72544df18c8a65de21ea7132a1a57bf35673

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
